CREATE TABLE IF NOT EXISTS TODOITEM(ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL, USERNAME VARCHAR(255) NOT NULL, TITLE VARCHAR2(255), DESCRIPTION VARCHAR2(255), STATUS VARCHAR2(255));
CREATE INDEX IF NOT EXISTS USERNAME ON TODOITEM(USERNAME);
CREATE INDEX IF NOT EXISTS ITEM_USERNAME ON TODOITEM(ID, USERNAME);


CREATE TABLE IF NOT EXISTS STATUS(NAME VARCHAR2(255) PRIMARY KEY NOT NULL, "SEQUENCE" INT);